apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-jhlee11
  namespace: database-pg
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: postgres-jhlee11
  template:
    metadata:
      labels:
        app: postgres-jhlee11
    spec:
      containers:
      - image: postgres:12
        name: postgresql
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_DB 
        - name: PGDATA #필수라고 함
          value: /var/lib/postgresql/data/pgdata                          
        ports:
        - containerPort: 5432
